### ISSUE TITLE
adding sha512 rounds to pam 

### ISSUE THREAD

**Issue by slimm609** [inversoft/2016-security-scripts#3]
the default number of rounds is 5000.   Increasing this number adds to the time it would take to brute-force or find a collision, while adding very little time to user login time.  The chance of finding a collision is very low but this is an easy step to reduce it even more. 

```
password	[success=1 default=ignore]	pam_unix.so obscure try_first_pass sha512 rounds=200000
```

**Comment by voidmain** [comment]
This really only matters if someone has the hash of the password and is brute force attacking it, but definitely a good idea.
